language: node_js
node_js:
  - "8.5.0"
cache:
  directories:
    - source/node_modules
script:
  - npm --prefix ./source install
  - npm --prefix ./source test
  - npm --prefix ./source run build
on:
  branch: master

before_deploy:
  - mv source/dist/index.html source/dist/index.php
  - cd source/dist
deploy:
  provider: heroku
  api_key: 7112dbcb-38b1-4d7c-b690-741a19aec3c4
  skip_cleanup: true
  local_dir: source/dist
  app: jelpzone-frontend  