language: node_js
node_js:
  - "8.5.0"
cache:
  directories:
    - source/node_modules
script:
  - npm --prefix ./source install
  - npm --prefix ./source test
  - npm --prefix ./source run build
on:
  branch: master